version: '3'
services:
  app:
    build:
      context: ./homework17
      dockerfile: Dockerfile
    privileged: true
    environment:
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - configserver
      - postgres
    networks:
      - nw
  configserver:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    privileged: true
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - nw
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - ":5432"
    networks:
      - nw
networks:
  nw: