management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics

app:
  someservice:
    active: true

spring:
  data:
    rest:
      base-path: /datarest
      detection-strategy: annotated

  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true